default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: allslavic
  password:

development:
  <<: *default
  database: allslavic_development

test: &test
  <<: *default
  database: allslavic_test

production:
  <<: *default
  database: allslavic_production

cucumber:
  <<: *test
